name: Build and deploy ASP.Net Core app to Azure Web App - hisup-app-24cs015

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: src/HiSUP

      - name: dotnet publish
        run: dotnet publish -c Release -o ./myapp
        working-directory: src/HiSUP

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: src/HiSUP/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hisup-app-24cs015'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .